### ISSUE TITLE
Component updating before parent component

### ISSUE THREAD

**Issue by perrin4869** [reactjs/react-redux#286]
First of all, I setup a demo repo of the problem here: https://github.com/perrin4869/react-redux-problem and am currently serving the demo at http://julian.dotcore.co.il

In that demo, you have the following component tree:

```
App
├── Foo
|   └── List
└── Bar
```

And the state is very simple: `{ list: (array | null) }`. If `state.list` is an array, `Foo` is render, if it is `null` then `Bar` is rendered. The problem is, when `state.list` gets turned from `[...]` to `null`, `Foo` gets re-rendered and throws an error because it can't render `<List list={state.list} />` (because it is null), and only a second later does `App` get re-rendered and `Foo` is exchanged with `Bar`.

Is it possible to setup this kind of project in a way so as not to throw that error? Of course, you could use `App` to pass `state.list` down to `Foo`: `<Foo list={state.list} />` which then passes the list down to `List`, but then you have to pass state down to components that don't really to know about it.

**Comment by gaearon** [comment]
Does the problem stay when you remove the transition group? It seems like you’re delaying rendering with transition group, and this is why you render `<Foo>` when it no longer has a `list`, which passes an undefined `list` to `<List>`.

>Of course, you could use App to pass state.list down to Foo: <Foo list={state.list} /> which then passes the list down to List, but then you have to pass state down to components that don't really to know about it.

The problem is that when you use a transition group, you want to retrieve data *above* it so that it can render data passed by props even when this data is no longer in the state. So this seems like a valid case for when you’d want to `connect()` a component above.

**Comment by gaearon** [comment]
Effectively you don’t want `Foo` to render the current state of the Redux store. (Because it gets empty during the transition!) Therefore you *want* it to be a presentational component that reads data from props.
