### ISSUE TITLE
connect()(Component) is interfering with styling

### ISSUE THREAD

**Issue by kristoferjoseph** [reactjs/react-redux#294]
## Synopsis
When using connect with a component the rendered result is missing styling applied.

## Expected results
Styles associated with a component are applied to the component

<img width="392" alt="screenshot 2016-02-19 11 05 05" src="https://cloud.githubusercontent.com/assets/76308/13185974/ac0bbc34-d6f8-11e5-833e-34ab196538fd.png">

<img width="523" alt="screenshot 2016-02-19 11 00 50" src="https://cloud.githubusercontent.com/assets/76308/13185934/81fc73b6-d6f8-11e5-8025-f8e6a29d495a.png">

## Actual results
Styles are not applied to the component due to connect wrapping the component

<img width="560" alt="screenshot 2016-02-19 11 00 25" src="https://cloud.githubusercontent.com/assets/76308/13185947/8d470718-d6f8-11e5-9774-702ed509321e.png">

**Comment by gaearon** [comment]
Hi, thank you for coming by! Alas, this is not enough information to help you.
Please show the component code, how you’re applying styles, etc.

**Comment by kristoferjoseph** [comment]
I am using https://github.com/gajus/react-css-modules to apply styles.
`CSSModules(connect()(Component))`

**Comment by gaearon** [comment]
It uses a very invasive approach of overriding methods on your class.
In general I would not recommend this approach.

Since it wants to override *your* class you need to apply it *before* `connect()`.

```js
class Stuff extends Component { }

export default connect(
  mapStateToProps
)(CSSModules(Stuff, styles))
```

**Comment by FredyC** [comment]
I've been fighting with this a lot in past too and eventually realized that what `react-css-modules` provide is not that great for included cost. I mean components shouldn't be that complex in general to require more than 2-3 css classes. Generally it seems better to just split that component into smaller ones. Doing manually `className={styles.myClass}` instead of `styleName="myClass"`is not that big deal compared to requiring `react-css-modules` in each component and wrapping resulting object with it.

And I am not even mentioning some other weird behavior I've run into during development essentially requiring to restart webpack process.

**Comment by kristoferjoseph** [comment]
I agree with what you are saying. @gaearon `react-css-modules` is invasive and @FredyC you are correct you _can_ go very far with vanilla css modules, but dasherized css class names i.e. `my-css-class-name` is a very common use case it supports. To me it felt like the lesser of two evils. I mean what if you want to include third party css? Thinking about writing a postcss plugin that rewrites the class names to camel case to fix this the 'easy' way. cc @gajus

**Comment by FredyC** [comment]
I am not using _dasherized_ css class name and never needed to add such 3rd party ones. However what about just writing `className={styles['my-css-class-name']}`? I agree it's not that pretty, but to me it still wins over adding the mess caused by `react-css-modules`.

Perhaps it might be a good way right after your `import styles from 'style.css';` to add just something like `const STYLE_INPUT = styles['my-css-class-name'];` It would be more verbose at one side, but in your JSX it would look nice and pretty again ... `className={STYLE_INPUT}`. Or instead of postcss you can just manually call some helper function here that would normalize names without dashes for a local use in the component.

**Comment by kristoferjoseph** [comment]
@FredyC Exactly. I've been using the `style['dasherized-classe-name']` approach. Thar definitely be dragons there though for brining on new devs etc. Not terrible, just a rake waiting to be stepped on in the middle of the room.
