### ISSUE TITLE
(Breaking change) Stop hoisting non-enumerable statics

### ISSUE THREAD

**Issue by gaearon** [reactjs/react-redux#310]
Issues like https://github.com/reactjs/react-redux/issues/163#issuecomment-192556637 are no fun and are exactly the reason why transferring arbitrary statics can be fragile.

We won’t back out of #127 now but we should at least stop hoisting non-enumerable statics in the next major version.

**Comment by nfcampos** [comment]
`hoist-non-react-statics` used to only hoist enumerable properties but switched to hoisting non-enumerables as well because in `class {static boo = 2}` babel used to transpile boo as non-enumerable. (see https://github.com/mridgway/hoist-non-react-statics/pull/3 and the linked issue)
I checked now and babel no longer does that, static properties are now enumerable, not sure when it was changed though.
so, I don't see any reason not to change this back to enumerables only

**Comment by gaearon** [comment]
Going to close this unless people hit more edge cases related to this.

**Comment by daltones** [comment]
In my application I created a component that extends another component's class. I guess that's not very common with react components, since composition is preferred in most cases.

So I have something like this:
```js
class MyBase extends React.Component {
  static baseStaticMethod() {
    return 'works';
  }
}

class MyComponent extends MyBase {
  static ownStaticMethod() {
    return 'also works';
  }
}

const Connected = connect()(MyComponent);
```
(transforming with `babel-plugin-transform-es2015-classes (loose: false)`)

And it results on this:
```js
Connected.WrappedComponent.ownStaticMethod(); // 'also works'
Connected.ownStaticMethod(); // 'also works'
Connected.WrappedComponent.baseStaticMethod(); // works
Connected.baseStaticMethod(); // TypeError: Connected.baseStaticMethod is not a function
```

When I was writing my app and reached that `TypeError` I thought “Okay, I just forgot again that this component is `connect()`ed…” But after that I found the _All the original static methods of the component are hoisted_ in the docs.

> We won’t back out of #127 now but we should at least stop hoisting non-enumerable statics in the next major version.

Probably there's more to consider, but I think that all hoisting of static methods should be deprecated in flavor of `.WrappedComponent.staticMethod()`.

I never like the fact that a consumer of some connected component must know about that and must use `getWrappedInstance()`, but I know it's necessary, and it's worst trying to hoist every instance member. So `WrappedComponent` could be the exactly equivalent for static members.
