### ISSUE TITLE
Initializing state dispatching actions in component, the right and the wrong way

### ISSUE THREAD

**Issue by srlopez** [reactjs/react-redux#322]
Studying 'React Native' & 'Redux', I wanted to initialize a 'State' in componenetWillMount() function to see with the data is rendered in my component.

The component is a 'smart component' and  'State' and 'Actions' are mapped to props.

The first time you instantiate the component, the 'State' is empty and then an Action is dispatched in componetDidMount() to set some values in the 'State', which should re-invoke render () and show mutations in the screen.
Well, the truth is that render() is not called, but the state is updated, so is not a Redux issue

Instead, if I dispatch the action in a SetTimer even in componenetWillMount() then render() is invoked, and also the State is updated correctly.

I don't think this is a good way. 

Wich will be the tight place to dispatch actions to initialize State?

```
export default class extends Component {
  componentWillMount(){
    // This is binded to dispatch(...)
    // But this way the action is dispatched but the stete recived remains unchanged
    this.props.formActions.update('required','required value')
    // This way the actions is dispatched and re-render the component
    //setTimeout(() => { this.props.formActions.update('url','https://mi/url/de_prueba') }, 0);
  }

  render() {
    const { values } = this.props.formState;
    const { update, reset } = this.props.formActions;

    return (
      <View style={styles.container}>
        <Form values={this.props.formState.values} update={update} reset={reset}>
          <FTextInput name='url' label='Prueba url' placeholder='url'/>
          <FTextInput name='email' label='Prueba email' placeholder='email'/>
          <FTextInput name='required' label='Prueba required' placeholder='required'/>
        </Form>
        <EasyRow navigator={this.props.navigator} >
          <EasyLink label='Back'/>
        </EasyRow>
      </View>
    )
  }
}
`

```

Really thanks in advance

**Comment by gaearon** [comment]
>Well, the truth is that render() is not called, but the state is updated, so is not a Redux issue

This actually *is* a React Redux issue because if what you say is true, it means the library erroneously bails out of causing a re-render when it should cause it.

Can you please submit a pull request with a failing test demonstrating this behavior?

**Comment by srlopez** [comment]
Yes, Dan @gaearon,
This is the [repo](https://github.com/srlopez/rntest), and in the [src/pages/TestForm.js](https://github.com/srlopez/rntest/blob/master/src/pages/TetsForm.js) you can see:

```
componentWillMount(){
    // This component is binded to dispatch(...)
    // 1.-  this way the action is dispatched but the stete recived remains unchanged
    this.props.formActions.update('name','TEST NAME')
    // 2. - This way the actions is dispatched and re-render the component
    //setTimeout(() => { this.props.formActions.update('url','https://mi/url/de_prueba') }, 0);
  }

```
Direct dispatching in point 1, does not reflect in screen (the field name remains empty), but delayed dispatching as in point 2, reflect the mutation in field URL (and in NAME  too if both lines of code are executed, without comment marks)

Talking about Redux, the 'scene' is connected in [App.js](https://github.com/srlopez/rntest/blob/master/src/App.js) lines 55-67
```
const store = configureStore();
const AppContainer = connectComponent(App);

//Root
export default class RootComponent extends Component {
  render () {
    return (
      <Provider store={store}>
        <AppContainer />
      </Provider>
    )
  }
}
```

And the `App` is on lines 21-53 of the same file, as a typical `Navigator` component, so all the scenes are 'connected' and the connectComponent is the typical  react-redux '`connect`' function in [AppContainer.js](https://github.com/srlopez/rntest/blob/master/src/AppContainer.js), just few lines ...

```
...
import { actionsCreators as formActions } from './redux/formActions'
...
export default function (component) {
  return connect(
    //state => state,
    (state) => ({  // state.xxxx <-- defined en ./store.js (index,js?)
      formState: state.form,
...
    }),
    //mapDispatchToProps
    (dispatch) => ({
      formActions:  bindActionCreators(formActions, dispatch),
...
    })
  )(component)
}
```
There is no doubt, the component is '`connect'ed` and Redux is well working, the trace display all the actions are dispatched. 

To test the behavior we are talking about, you know, clone the repo, run it (you can run using `npm run nurse`), next on first screen, press 'Go to Form' and ... you pass throw the `componentWillMount()` above.

If you need some help, this Form is inspired by @kasprownik and his code in this [repo](https://github.com/kasprownik/react-forms-tutorial) write in ReactJS and well explained in this [http://x-team.com/2016/02/tutorial-forms-in-react-and-redux/](blog)

**Comment by rhagigi** [comment]
**note I haven't run the code, but just from static analysis reading, I think this is what's happening**

@gaearon - In @srlopez 's example, he's calling out to an action, which changes the redux state synchronously, *during* the component lifecycle. In react-redux, the connect wrapper component only begins subscribing to store updates on the *connect* component's componentDidMount. https://github.com/reactjs/react-redux/blob/master/src/components/connect.js#L212

Due to react lifecycle rules, this always will happen *after* componentDidMount of the client (which is why neither sending the action on componentWillMount or componentDidMount worked).  The code that seems to exist to address this issue is that you're calling this.handleChange() after subscribing, to ensure that if there are new changes, we set the new state.

From what I can tell, this *should* set both the new state and sets `this.hasStoreStateChanged = true`. That's where the issue is. The expectation is that when shouldComponentUpdate() runs, `return !pure || this.haveOwnPropsChanged || this.hasStoreStateChanged` should return true because the storestate has changed. But, because shouldComponentUpdate runs *after* the initial render (calling setState in componentDidMount triggers a double render -- only the second one gets the new state), and the initial `render()` sets `this.hasStoreStateChanged = false`, we never get the second render.
