### ISSUE TITLE
must return an object. Instead received [object Object].

### ISSUE THREAD

**Issue by EasonWang01** [reactjs/react-redux#334]
hi,I'm new to this

the error message is 
`browser.js:40 Uncaught Invariant Violation: `mapStateToProps` must return an object. Instead received [object Object].`
1.
```
		case 'TOGGLE_TODO':

			
		return	state.todos.map(function(state){
				if(state.id!==action.id){
				return	state
				};
				
				return {...state,completed:true}
			});
```
(from egghead )
this will throw the error,but I don't know why.

But if I not using `return` before `state.todos.map` it is fine

2.
```
		case 'TOGGLE_TODO':

			
		  	state.todos.map(function(state){
				if(state.id!==action.id){
				return	state
				};
				
				//return state.completed=true}
				return {...state,completed:true}
			});

```
if I change to this it will not change the store 

3.
only 
```
		case 'TOGGLE_TODO':

			
		  	state.todos.map(function(state){
				if(state.id!==action.id){
				return	state
				};
				
				//return state.completed=true}
				return state.completed=true
			});
```
and
```
		case 'TOGGLE_TODO':

			
		  	state.todos.map(function(state){
				if(state.id!==action.id){
				return	state
				};
				
				//return state.completed=true}
				return Object.assign(state,{completed:true})
			});

```

can successfully update the store and no error message,but this will also change the prev state,

how can I change this code?  Thanks for reply.

**Comment by gaearon** [comment]
If you found the solution please share it in a comment so other people who find this issue know how you solved it. Thanks!

**Comment by EasonWang01** [comment]
I was using below works good ,but still don't know why others give error when it return `[object Object] `but still  says `must return an object`

```
case 'TOGGLE_TODO':


      return Object.assign({},state,{todos:state.todos.map(function(state){
                if(state.id!==action.id){
                return  state
                };

                return {...state,completed:!state.completed}
           
			}) }
      )
```

**Comment by gaearon** [comment]
Why are you posting the reducer code? The error says `mapStateToProps` returned something that isn’t a plain object. Not the reducer.

My guess is your `mapStateToProps` returns something like `state.todos` which will not work. The point of that function is to provide props to component, so it has to return an object with those props. Rather than pass `state.todos` you would probably want `{ todos: state.todos }`.

If this is the case, we need to make a better error message that detects arrays. Contributions are welcome.

**Comment by alex-deas** [comment]
The problem here is that the error message isn't clear enough, an object is being passed in but it isn't a plain object until EasonWang01 uses `Object.assign()`. `checkStateShape` calls `_.isPlainObject` which requires `Object.prototype == null` or to have been created with `Object.constructor`. The error message could probably updated to read `%sToProps must return a plain object. Instead received %s`

The wording for `computeMergedProps` could be updated as well to reflect this.

**Comment by EasonWang01** [comment]
the mapStateToProp is look like this
```
import React, { Component } from 'react'
import TodoInput from './TodoInput.js'
import TodoList from './TodoList.js'
import {connect} from 'react-redux'




class App extends Component {

  render() {
    return (
      <div>
        <h1>Todo list</h1>
        <TodoInput />
        <TodoList  todos={this.props}/>
     
  
      </div>
    )
  }

}
function  mapStateToProp(state){

	return state
}


export default connect(mapStateToProp)(App)

```
I guess it might be that I'm not using combineReducer so I need to return the full state to state
 ( ΄◞ิ .̫.̫ ◟ิ‵)y

**Comment by gaearon** [comment]
Can you provide a full project reproducing the problem on GitHub? These pieces don't quite add up in my mind. For example it is strange you are passing the whole props object as todos prop down.

**Comment by EasonWang01** [comment]
Hi,  https://github.com/EasonWang01/Redux-tutorial/tree/link  it's a origin version.

in  Redux folder=> reducer.js

I try to change line 18~26 make it back to two days ago,but the error don't show again,don't know.

But I thinks it's not a big problem need to care,maybe just some return object type that I miss.
( ´ ▽ ` )b

**Comment by EasonWang01** [comment]
update

change reducer.js  line 4~15 to below
```
switch(action.type){
		case 'ADD_TODO':
			
			return(	Object.assign({},state,{
				todos:[...state.todos,{
				  text:action.text,
				  completed:false,
				  id:getId++

				}]
			})
			)
```
and click `initial for demo`,then the error will appear

( ^ ᴗ ^ )ε

**Comment by EasonWang01** [comment]
Hi,could I ask other basic question beside this~

that I want to split the reducer function and do something like below,the project is the same as I provide above,only change reducer.js.
But it give me `TodoList.js:63Uncaught TypeError: Cannot read property 'map' of undefined`

Sorry for this basic question,but I don't know is it miss something.Thanks for reply.
```
let getId = 1 ;


 export default function reducer (state,action) {
	return Object.assign({},state,{
		visbility:reducer2(state="SHOW_ALL",action),
		todos:reducer1(state=[],action)
	})
}


 function reducer1(state,action){
	switch(action.type){
		case 'ADD_TODO':
	
			return [...state.todos,{
				  text:action.text,
				  completed:false,
				  id:getId++

				}]
		
			
		case 'TOGGLE_TODO':

      return state.todos.map(function(state){
                if(state.id!==action.id){
                return  state
                };

                return {...state,completed:!state.completed}
           
			}); 
      
}}

 function reducer2(state,action){
  switch(action.type){
      	case 'SET_VISBILITY_FILTER':

      	return action.filter
	

				

		default:
			return state;

	}

}

```

**Comment by EasonWang01** [comment]
But one thing I found is when some error occur in reducer the console.error will always point to some component file rather than reducer.js file.

**Comment by gaearon** [comment]
Normally you return an object like `{ todos: Array<Todo> }`:

```js
        case 'ADD_TODO':

            return( Object.assign({},state,{
                todos:[{
                  text:action.text,
                  completed:false,
                  id:getId++

                },...state.todos]
            })
            )
```

However when handling `TOGGLE_TODO`, you return just an `Array<Todo>`:

```js
        case 'TOGGLE_TODO':

  return  state.todos.map(function(state){
                if(state.id!==action.id){
                return  state
                };

                return {...state,completed:true}
            });
```

This is missing `Object.assign({}, state, { todos: ... })`.

Then this `state` gets returned from `mapState()` which is where the error fires. Fixing the reducer to return the object would fix the problem. I also suggest you to use reducer composition as Egghead series shows, rather than put all the code into a single big reducer.

Hope it helps!

**Comment by EasonWang01** [comment]
thanks!
