### ISSUE TITLE
if `componentDidMount()` throws, subscription in `connect()` fails

### ISSUE THREAD

**Issue by jokeyrhyme** [reactjs/react-redux#357]
I have a reduced test case here:
- http://codepen.io/jokeyrhyme/pen/wGjxNo

When my `componentDidMount()` method throws, the store subscription set up within `connect()` doesn't work, so neither my `mapStateToProps()` function nor `render()` method are called.

As it happened, in this particular case I wasn't able to review the console log live, so I did not immediately notice that my `componentDidMount()` was broken.

Should the `connect()`ed component be more resilient to lifecycle bugs caused by the wrapped component?

I'm not really sure there's much that can be done here. But I figured I'd leave a trail just in case someone else has a similar problem.

**Comment by gaearon** [comment]
When React officially supports error boundaries (https://github.com/facebook/react/pull/5602 started work on this, and you can track it in https://github.com/facebook/react/issues/2461), you’ll be able to catch those errors. We can’t really do anything on the library level here because it’s impossible to guess every possible combination of things going wrong.
