### ISSUE TITLE
re-render when user react-native NavigationExperimental/NavigationLegacyNavigator.js

### ISSUE THREAD

**Issue by chenxiaohu** [reactjs/react-redux#365]
When use NavigationExperimental/NavigationLegacyNavigator.js as navigator, all container components connected to redux store rendered by any action. 
Old navigator has not this problem.

**Comment by gaearon** [comment]
Can you provide an example that reproduces this?

**Comment by chenxiaohu** [comment]
[src.zip](https://github.com/reactjs/react-redux/files/231960/src.zip)

this example toggle navigator can reproduces.

**Comment by gaearon** [comment]
I don’t know React Native well. How do I launch this repo?

**Comment by chenxiaohu** [comment]
Do you ever try any React Native project, even Get started project?

**Comment by gaearon** [comment]
Yeah. But usually they come with Xcode projects, don’t they?

**Comment by gaearon** [comment]
Okay, I got it to run. Can you please clarify *which exactly* actions you do not expect to cause components to re-render?

**Comment by gaearon** [comment]
If I change `renderList(list)` in `Comment.js` to dispatch an action on click, I don’t get any log messages about re-renders:

```js
  renderList(list) {
    let result = [];
    list.map(i => {
      result.push(<TouchableOpacity key={i.id} style={styles.row} onPress={() => {
        this.props.dispatch({
          type: 'test'
        })
      }}><Text>{i.title}</Text></TouchableOpacity>);
    });
    return result;
  }
```

Therefore, “any action” does not cause “all container components” to re-render, so it looks like there is no bug here.

When I run the app for the first time, I see this:

```
@Render Root.....
Post.js:58 @@Render PostList
App.js:34 REQUEST_POST_LIST
Post.js:58 @@Render PostList
App.js:34 RECEIVE_POST_LIST
Post.js:58 @@Render PostList
```

It looks correct to me: we first render the initial state, which is an empty screen, then we `REQUEST_POST_LIST` causes a re-render because there is a loading indicator now, and then `RECEIVE_POST_LIST` causes a re-render because the list is ready.

If I open a post’s comments, I see this:

```
@@Render CommentList for post: 4
App.js:34 REQUEST_COMMENT_LIST
Post.js:58 @@Render PostList
App.js:34 RECEIVE_COMMENT_LIST
Comment.js:63 @@Render CommentList for post: 4
```

The initial `@@Render CommentList for post: 4` is caused by the empty list appearing. It looks fine to me. The second `@@Render CommentList` also makes sense to me here: the comments are loaded so it’s time to render the actual list.

The one that doesn’t quite make sense to me is `REQUEST_COMMENT_LIST` causing `@@Render PostList. Requesting comments shouldn’t re-render the posts.

I dug into why this happens, and it seems like [returning a cached element in `render()`](https://github.com/reactjs/react-redux/blob/253ce8b3068d9d9bfe55f70a6f18a5fde313b326/src/components/connect.js#L324-L326) is not enough to prevent a re-render in some cases when there is an additional context between `<Provider>` and the `connect()`ed component [because of this check in `ReactReconciler`](https://github.com/facebook/react/blob/5ddfee8cfece399d686862f2ac2796b63eb78f00/src/renderers/shared/reconciler/ReactReconciler.js#L98).

I don’t fully understand in which cases this happens yet so I’ll file a separate issue for the future.
For now, you have two options to avoid this:

### Option 1

Remove `ownProps` from your `mapStateToProps` function in `Post.js`.
This will turn on the optimizations earlier, and that code path will be avoided altogether.

```js
function mapStateToProps(state) { // , ownProps
  let {list, isFetching} = state.postList || {isFetching:true};
  return {
    isFetching,
    list
  };
}
```

### Option 2

Add a custom `shouldComponentUpdate()` function to `Post.js` because React Redux could not optimize it in this particular case, and you need to do it manually.

```js
import shallowCompare from 'react-addons-shallow-compare'

class Post extends Component {
  shouldComponentUpdate(nextProps, nextState) {
    return shallowCompare(this, nextProps, nextState)
  }
```

I hope this helps!

**Comment by chenxiaohu** [comment]
Great! your answer is prefect for me. thanks:)
