### ISSUE TITLE
Can a component dispatch actions before its children render?

### ISSUE THREAD

**Issue by sean-shirazi** [reactjs/react-redux#374]
I'm trying to store some props from react-router into the store and use it somewhere down the hierarchy. My tests show that in the code below, when app receives props and dispatches an action, the child will receive the new store state when it's rendered.
But I just want to make sure that there won't be any race conditions or any other surprises. Also if you think there is a better way to achieve this please let me know.
Thanks :-)

``` jsx
let App = React.createClass({
    render() {
        // imagine Child is many levels down
        // the hierarchy
        return <Child />;
    },
    componentWillReceiveProps(newProps) {
        this.props.dispatch({
            type: 'TEST',
            // this comes from react-router
            test: newProps.location.pathname,
        });
    }
});

let Child = React.createClass({
    render() {
        return (
            <h1>{this.props.test}</h1>
        );
    }
});


App = connect()(App);

Child = connect(
    state => ({
        test: state.test,
    })
)(Child);

```

**Comment by gaearon** [comment]
We don’t recommend this. If you are duplicating data from React Router in Redux store, it is extremely likely you’ll have race conditions. I recommend that you don’t do that, and instead use `withRouter()` higher order component to inject router params (works since React Router >= 3.0 beta), and use *that* as the source of truth. I recorded a few free lessons on how to do it:

* https://egghead.io/lessons/javascript-redux-filtering-redux-state-with-react-router-params?course=building-react-applications-with-idiomatic-redux
* https://egghead.io/lessons/javascript-redux-using-withrouter-to-inject-the-params-into-connected-components
