### ISSUE TITLE
Props are missing from components when using React.cloneElement to add props to children

### ISSUE THREAD

**Issue by DWboutin** [reactjs/react-redux#378]
Hi, 

I'm having a main page "Registration" who is connected with `import { connect } from 'react-redux';`. I pass the props i want to the children of this page (3 differents pages/forms) with `React.cloneElement`.

```javascript
{React.cloneElement(this.props.children || <div />, { key, savedForm, dispatch, salutations, bestTimesToCall, paymentMethods, minimumPayouts })}
```

When i build in development environnement, i got these errors for each child and each props needed into them:
```
Failed propType: Required prop `dispatch` was not specified in `ConnectionInfosContainer`. Check the render method of `RouterContext`.
```
"ConnectionInfosContainer" is the direct child of "Registration". Why i got these errors? All is working well and if i build my app in Production environnement, all theses errors are gone.

Should `connect()` do it work before rendering the component?

**Comment by gaearon** [comment]
You specified `dispatch` as a required prop. However, React checks props *at the time an element is created*. So even if you `cloneElement()` later, you’ll see a warning.

There is no way to solve this because we never know if `cloneElement()` is called in the future. You can suppress the error by defining something like

```js
ConnectionInfosContainer.defaultProps = {
  dispatch() {}
}
```

so that you get a no-op by default.

In the future, we recommend that you ask questions on StackOverflow first, and file issues if you’re confident the bug is in the library.
