### ISSUE TITLE
with same props in shouldComponentUpdate

### ISSUE THREAD

**Issue by aDeadFish** [reactjs/react-redux#385]
I'm having an issue with Redux, when I try to implement shouldComponentUpdate for a component, this.props already holds the same value as nextProps。I don't understand why this would happen. Is there any way around it?

**Comment by gaearon** [comment]
It is hard to say anything because there is no code sample and it is not clear how you compare the props. I will close as this appears to be a usage question, and we ask that you ask them on StackOverflow instead. This is a bug tracker and not a support forum. That said feel free to post a link to your question with example code and I'll try to take a look. Thanks!
