### ISSUE TITLE
react native error: import React from 'react-native'    is not working in react native version 0.26

### ISSUE THREAD

**Issue by alex306314** [reactjs/react-redux#394]
as question title

**Comment by gaearon** [comment]
Hi!

Is there any particular reason you filed this issue in `react-redux` repo?
It has no relation to React Native or React itself.

If you have problems updating to React Native 0.26, I think it is a good idea to open [React 0.26 release notes](https://github.com/facebook/react-native/releases/tag/v0.26.0) since that’s how you can find out what changed. The release notes on that page say:

>React API must be now required from react package (previously a warning on 0.25)

So you need to change `import React from 'react-native'` to `import React from 'react'`.

Anyway, this is an issue tracker for an entirely unrelated library, so I’m closing, and won’t be able to help further here. Please feel free to ask on StackOverflow if you have further questions! Cheers.
