### ISSUE TITLE
Can i get store in sub-components constructor?

### ISSUE THREAD

**Issue by JIM-CHEN** [reactjs/react-redux#401]
Hi everyone,

In my react app, multiple view shared few state, but each view (state) is complex and have multiple sub-components. Therefore, i also need redux to manage ui state.

I want to call combineReducer in sub-components' constructor to load reducer dynamically and also can have a chance to delete some parts of state in destroy callback via reducer if needed. To use redux with redux-ignore in sub-components is also good for me.

I found store can be get in componentDidMount from [issue](https://github.com/reactjs/redux/issues/239), but i think it's more make sense for me to combine reducer in constructor.

Not very sure my opinion is correct or not.

**Comment by markerikson** [comment]
Hi.  First off, this is really a usage question rather than a bug or issue with Redux.  As such, it should be asked over on Stack Overflow.  I'm going to close this, but if you do post a Stack Overflow question, go ahead and paste the link in here.

That said, there's a number of libraries which can help you manage per-component state in your Redux store.  See my [Redux addons catalog](https://github.com/markerikson/redux-ecosystem-links) for some possibilities, particularly the [Local/Component State](https://github.com/markerikson/redux-ecosystem-links/blob/master/component-state.md) and [Reducer](https://github.com/markerikson/redux-ecosystem-links/blob/master/reducers.md) pages.

**Comment by JIM-CHEN** [comment]
Thank you very much!
