### ISSUE TITLE
Easy way to map getState() to this.props.getState() for dependency injection?

### ISSUE THREAD

**Issue by brianboyko** [reactjs/react-redux#419]
Hello. 

I'm working on a piece of code called "reduxify" which I hope to publish as an NPM module, that helps take away some of the boilerplate of using react-redux on large projects.  

The problem that I'm running into is that I can't seem to find a way to map getState() to props.  This is somewhat important for the design pattern I'm working with. 

Specifically, in order to keep my "utilities" unit-testable in isolation - that is, without having to import the store, I was using dependency injection. That is, if I had a file called ./utilities/api.js, it would be written something like this: 

```
export default function api = (dispatch, getState) => {
  const getRandomNumber = (req) => {
    request(req).then((num) => {
       dispatch(addNumber(num));
       let currentState = getState(); 
       if (currentState.number % 2 === 0 ){
         dispatch(evenAction())
       } else {
         dispatch(oddAction()); 
       }
    })
  }
  return {
     getThingy,
  }
}
```

This way, I can mock both dispatch and getState.  As for the use in dev/production, it would be something like this:

```
import apiRoot from './api'

class NumberThing extends Component{
  constructor(props){
     let api = apiRoot(this.props.dispatch, this.props.getState)
  }
  this.handleClick(){
     api.getThingy(this.state.whatever)
  }
}
```

I'll be writing v. 1 of Reduxify without this functionality, but I'm thinking there's gotta be a way to do this without exporting getState() from the store and importing it into the component.  

Your thoughts?

**Comment by markerikson** [comment]
Hi, Brian.  I know we talked about something like this a while back.  Is there any reason you aren't just using thunks?  Because thunks are middleware-based, the thunk functions receive `getState` and `dispatch` automatically.  Also, with the newer redux-thunk v2.1.0, you can automatically inject additional arguments into your thunk functions, such as specific AJAX API wrappers or something.

**Comment by markerikson** [comment]
So glancing at https://github.com/brianboyko/reduxify , a couple thoughts:

- Semantically, it's not "reducers" that you're picking - it's the _keys in your state_ (which may or may not have specific reducer functions assigned to handle updating them)
- Everyone's apps and setups will vary, but I would think that much of the time components would need much more fine-grained data than an entire slice of state
- I know that I'm the one who wrote that `prepareActions` utility in the first place and showed it to you, but fwiw, I'm starting to re-think my approach on including bound actions as a prop named "actions", because it's starting to cause the plain version of my components to sorta-kinda "know" that their props are coming from Redux.  Still debating the pros and cons.

**Comment by brianboyko** [comment]
While thunks are very useful for asynchronous actions, they don't seem to me to be the right tool for this type of usage.  Not every "utility" function that I would write would necessarily be asynchronous, 

Truth be told, I actually think asynchronous actions can cause a big problem if you're trying to use Redux to replay the state the user experienced it in.  That is: if actions can be asynchronous, depending on the variable delay, the actions might be dispatched *out of order*, which can lead to debugging problems.  ("Hey, why does it work for me, here in London, but not for my partner in Taipei?")

**Comment by markerikson** [comment]
Note that the since the DevTools need to be placed last in the enhancer sequence, right before the real store, they only replay actions that actually reached the reducers.  So, the actual _changes to state_ would be the part that gets replayed, not stuff that got intercepted by middleware and redirected.

Also, thunks can totally serve for both true async behavior _and_ more complex synchronous logic as well.  I've got several examples of thunk usage over at https://gist.github.com/markerikson/ea4d0a6ce56ee479fe8b356e099f857e, and note that three of the four are just synchronous code, not async.  So yes, this is _exactly_ one of the use cases that thunks were intended for.

**Comment by brianboyko** [comment]
Ah, I don't have access to the dev tools where I work, so building a custom solution was necessary.

**Comment by markerikson** [comment]
Gotcha.  Out of curiosity: I know that you're working in a fairly restricted environment, but is there anything preventing you from downloading stuff like the Redux DevTools package "manually" and including it in your project?

**Comment by brianboyko** [comment]
Only that I've tried it, and it doesn't work for whatever reason. I suspect
it is because Redux Dev Tools attempts to recalculate the state from
scratch by running through all the actions, every time you move backwards
in the timeline, which is problematic for an application that can have up
to 3000 actions.
