### ISSUE TITLE
Multiple stores for complicate page

### ISSUE THREAD

**Issue by valery-bary** [reactjs/react-redux#478]
This issue discussed very match, but I don't know how I can solve my problem with one store. I have some report page with filter and a lot tables for every our brand. So page have a lot data. Filter have several controls for define filter and Generate button. If I have one store so every change on filter takes about 5 sec. with no data changed. I want to have different stores for filter and for every brand. So change of filter (without generate data) will not case to render all page with data. Tables of Brands have page selectors. So select specific page of some brand don't fire render of all page. 
My question: can I create several stores or there any other solution? Because I can't run render all page for   every action.

**Comment by timdorr** [comment]
The answer isn't breaking up how you store the data, but how you query it out. It's still a big bundle of state to work with, even if you slice it into multiple stores.

I would look into a library like reselect for optimizing and caching how you're querying that data. You should also break up your connected components so that you don't have everything running through one single `connect`, as that will likely slow you down as well.

**Comment by talaikis** [comment]
This feature has more use cases than just for complex site.  For example, you also use persistors and want to  delete on on sign out and leave another after the session.

**Comment by markerikson** [comment]
@talaikis we really, _really_ mean it when we say there should only be one store in an app :)

(Also, commenting on an issue that hasn't been touched since 2016 isn't going to be seen by anyone, and this really isn't even a React-Redux topic - it's a Redux core topic. If you have a specific use case that you'd like help on, I'd suggest asking in the Redux "Discussions" section.)
