### ISSUE TITLE
shallowEqual() returning false when comparing empty values

### ISSUE THREAD

**Issue by marceux** [reactjs/react-redux#481]
I have a state that returns an empty array under specific circumstances for a specific property. Let's call this property, `selected`.

I dispatched an action that triggered a state change, but did not alter `selected` at all. Now, every connected component that relies on `selected` is rendering.

When `shallowEqual()` compares the states and their keys and their values, empty Arrays and empty Objects will fail every time.

```
if (!hasOwn.call(objB, keysA[i]) ||
     objA[keysA[i]] !== objB[keysA[i]]) {
  return false
}
```

Is this intended behavior? Should I submit a pull request?

**Comment by timdorr** [comment]
Keep in mind that `[1, 2, 3] === [1, 2, 3]` is `false` because each empty array is a unique instance and the equality check is looking for each side to be the exact same instance, similar to a plain object equality check. 

So, if you have a reducer that does `return []` somewhere, keep in mind that is new instance of an empty array and will not equal an empty array created by the previous run of the reducer. Instead, if you define something like `const emptyArray = []` outside of your reducer function and `return emptyArray`, you will be providing the same instance of the array and [the initial equality check](https://github.com/reactjs/react-redux/blob/68a4f2b78671329e10bfca87f8f1c82cc8690459/src/utils/shallowEqual.js#L2) will catch things first.
