### ISSUE TITLE
The reducer function itself is being run twice for a single dispatched action

### ISSUE THREAD

**Issue by sniperyan** [reactjs/react-redux#494]
My error code is on the repo:[https://github.com/sniperyan/react-cnode](https://github.com/sniperyan/react-cnode)
In my code,you can find test button in `js/containers/listApp/index.js` , there is a click handler named `testFunc` , in this function, I dispatch an action .  When you click the button, the actionCreator will trigger the reducer ` js/reducers/indexList/index.js` . I add a  'console.log' and you can see the console of your web browser , you can see the 'console.log' run twice for a single dispatched action.
I attempt to solve this problem and find one method. I find when the ruducer run twice , there must be two listeners in `reateStore` in the package of `redux` .  I removed the `mapStateToProps` in my `connect`  function of my containers , i refer to the code in repo:[https://github.com/reactjs/redux/tree/master/examples/async](https://github.com/reactjs/redux/tree/master/examples/async), i see there is no `mapStateToProps` and the demo can run correctly , i compare my code to the examples of `redux` but i can not find mistake.
You can clone my code in the repo `react-cnode` at the beginning of this issues,after install npm modules and run the webpack, you can input `localhost:8080/` in you web brower , click the test button and the console of web browser will print the log twice 

Versions: 
"react-redux": "^4.4.5",
"redux": "^3.5.2",

**Comment by markerikson** [comment]
Ah.  I see the problem.  You're accidentally double-dispatching the same action.  Let me give some background info, then I'll explain what the problem is here:

I have an example of equivalent ways to dispatch an action, at https://gist.github.com/markerikson/6c7608eee5d2421966d3df5edbb8f05c .  Note that we go from, roughly,  `dispatch({type : "SOME_ACTION"})`, to `const theAction = someActionCreator(); dispatch(theAction);` to `const preBoundActionCreator = bindActionCreators(someActionCreator, dispatch); preBoundActionCreator();`.

In other words, when you use `bindActionCreators`, it calls your function _and immediately calls `dispatch`, passing in what your action creator returned_.  That means that you do _not_ have to actually call `dispatch` yourself - the bound action creator does that automatically.

Second, when you call `dispatch`, it normally returns whatever you passed in.  Middleware can change that.  This is useful for things like a thunk that returns a promise - you can do `dispatch(thunkThatReturnsAPromise()).then(value => doSomethingWith(value))`.

So here's what's happening.  You are using `mapDispatch` to bind your `indexList` actions.  That's fine.  However, your component uses it this way: `dispatch(actions.testFunc());`.  The `testFunc` function is already bound, so that dispatches the action once.  Then, the action is returned from the first `dispatch` call, and is passed straight to the second `dispatch` call.

All you need to do here is just call `actions.testFunc()`, and it should work fine.
