### ISSUE TITLE
how to re-render when props update?

### ISSUE THREAD

**Issue by clindsey** [reactjs/react-redux#539]
I'm trying to figure out how to update the modal after it's been displayed, like to update a price estimate value.  Right now I'm able to `modal.add(myComponent, {})` to create a modal and render `myComponent` but I can't figure out how to update the component.  I could remove the modal and display it again with the new props but that would discard the user updates inside the modal, such as form fields.

I'm currently getting around this issue by using `connect()` on `myComponet` to link it directly to the store, but I'd prefer to use a basic component and not a redux container.  What's the best way to do this?  Maybe I should always specify a generic container for the modal and one of the options will be the actual component I want displayed?  I feel like the problem will be that the container will need to know about every property any modal will need and will pass those to every modal it displays.

**Comment by markerikson** [comment]
Uh... this question needs a lot more context to make sense.  What modal?  What's `modal.add`?

For that matter, this is really a usage question, and should be asked on Stack Overflow, since it's not a bug or a feature request.

It sounds like you might want to go read Dan Abramov's description of a generic modal dialog manager in Redux.  See http://stackoverflow.com/questions/35623656/how-can-i-display-a-modal-dialog-in-redux-that-performs-asynchronous-actions/35641680 , and a couple other similar articles at https://github.com/markerikson/react-redux-links/blob/master/redux-techniques.md#ui-and-widget-implementations .

**Comment by clindsey** [comment]
@markerikson oops, I meant submit this to a completely different project, I guess I had the wrong window open.  my bad

**Comment by markerikson** [comment]
Gotcha.  Out of curiosity, what project?

**Comment by clindsey** [comment]
https://github.com/diegoddox/react-redux-modal
