### ISSUE TITLE
mapStateToProps not called after actions are executed

### ISSUE THREAD

**Issue by tedjames** [reactjs/react-redux#545]
So I've been trying to wrap my head around this issue for 8+ hours with no progress :(

I want to toggle a material-ui drawer by mapping a boolean from my redux store to my ButtonBar.js container. From there, I'm passing this.props.chatVisible down to the ChatButton component that then takes that boolean and sets it to the open property of my material-ui drawer. 

Comparing it to previous projects of mine, everything seems like it should be working fine. Unfortunately, this.props.chatVisible never updates beyond initialization. It always stays as whatever the default value is supposed to be (in this case, I've set the default value of chatVisible to true).

Here's the repo I'm working with: https://github.com/tedjames/creativeHomePortal

The affected components (ButtonBar.js and ChatButton.js) are located in /src/Components/Common/Header/rightSection

I logged global state after initialization and after each time I click ChatButton(thus firing the ToggleChat action). I also logged this.props.chatVisible from the ChatButton component every time I push it and the action fires:
http://imgur.com/a/bWBUa

This shows that the action and reducer are working as expected but that the chatButton component never receives the newly updated piece of state.

**Comment by markerikson** [comment]
Your reducer is being mutated.  The first argument to `Object.assign()` will be the target that everything is copied onto.  So, in order to properly do immutable updates, you need to pass a new blank object (or array) in as the first argument, the "old" object as the second argument, and any "new" values as the third argument, like: `const newState = Object.assign({}, oldObject, {someValue : 123}).  Your toggle reducer is currently doing `return Object.assign(state, newToggles);`, which is directly mutating `state`.

I'd encourage you to read http://redux.js.org/docs/faq/ReactRedux.html#react-not-rerendering and http://redux.js.org/docs/recipes/reducers/ImmutableUpdatePatterns.html , which explain how to make immutable updates properly.

**Comment by tedjames** [comment]
Thank you so much! Finally got it working 👍
