### ISSUE TITLE
is calling dispatch twice in an event handler an anti-pattern?

### ISSUE THREAD

**Issue by bochen2014** [reactjs/react-redux#549]
I have a contrived example. as below
```
//actions.js
export function add(){
   return { type:'add'}
}
----------------------------------------

//reducer.js
const reducer = (state={}, action)=>{
  switch(action.type){
     case 'add':
        return Object.assign({}, { counter:   state.counter +1 }) 
     return state
 }
}
---------------------------------------------
//component.js
import {add} from './actions'

const myComponent = props=>{
        const onClick= event=>{
               add()  // dispatch action add once
               add()  // dispatch action add twice
}

return (<div>
   <span> {props.counter}</span>
   <button onClick={onClick}>Click</button>
</div>)
}

const mapStateToProps = state=>(counter: state.counter)
export default  connect( mapStateToProps,{add}) (myComponent)
```

As shown above, clicking the button will cause  `action add` to be dispatched twice, each dispatch will cause component to be re-rendered.  Is there any performance concern in above code? is it an anti-pattern or a common practice?  

I assume it's a common practice.  Because it is everywhere in `redux-thunk`, i.e. we dispatch a beginFetch action and fendFetch action within a button click event , with the only difference being `redux-thunk` dispatch 2 actions asynchronously, but that shouldn't matter.

Just to verify my understanding of what's happening behind the scene  is correct:
```
dispatch -> reduce store -> connect component onChange ->componentWillReceiveNewProps -> register a re-render and immediately return;
dispatch again -> reduce store -> connect component onChange ->componentWillReceiveNewProps -> register a re-render and immediately return;
requestanimationframe -> component render ( which include both changes)
```

**Comment by gaearon** [comment]
It's okay but if you need to do dispatch more than a couple of actions I’d recommend rewriting your code so that there is just one action, and different reducers react to it.

Indeed it's not very good perf-wise although there is a [simple solution](https://github.com/tshelburne/redux-batched-actions) (and also a more [complex solution](https://github.com/tappleby/redux-batched-subscribe)) to that.

Of course, with async requests you *have* to dispatch twice, but you also want to update UI twice (to show a loading indicator and to hide it). So in that case it matches your intention.
