### ISSUE TITLE
Default parameter for ownProps causes it not to be passed

### ISSUE THREAD

**Issue by atkinchris** [reactjs/react-redux#623]
If a default parameter is provided for `ownProps` it will not be passed to `mapStateToProps`. For example:

```
const mapStateToProps = (state, ownProps) => console.log(ownProps)
// real ownProps

const mapStateToProps = (state, ownProps = {}) => console.log(ownProps)
// undefined
```

This is due to default parameters not being counted in `Function.length`, which causes [`proxy.dependsOnOwnProps`](https://github.com/reactjs/react-redux/blob/3c5c80e757c4f6e4127fb10d5b6ccd8c88aead6c/src/connect/wrapMapToProps.js#L41) to return false.

Is this intended behaviour?

**Comment by markerikson** [comment]
That's... an interesting question.

Off the top of my head, I would say "yes, it's intended".  Admittedly, the way `connect` relies on the function length as a signal is kind of a bit hacky in a way, but the intent is definitely that if you define `mapState` with two parameters, `connect` will make sure that it takes whatever props were given to the wrapper component and pass them to `mapState`.  So, if two params are declared, you should get a valid `ownProps` param even if it's an empty object.

If you're wanting to ensure that a specific prop always exists so that you can use it, I think your best options are either to declare default props on the connected component itself, or use destructuring assignment with defaults inside of `mapState`.

**Comment by atkinchris** [comment]
I assume that's for performance - so Redux can know if a component _uses_ `ownProps` - and if not, not cause it to re-render when `props` do change but `state` doesn't?

I admit, on re-reading the docs, it can be interpreted from them ("If `ownProps` is specified as a second argument, its value will be the props passed to your component"). It does cause unexpected behaviour, if you don't know it uses `Function.length` and understand how that treats default parameters - though, as you say - if you ask for `ownProps`, you'll never get `undefined`.

**Comment by markerikson** [comment]
Yeah, it's definitely a perf thing - if you don't ask for `ownProps`, your `mapState` only gets called when the store notifies subscribers.  If you _do_ ask for `ownProps`, it will also get called every time the incoming props change as well.

If you've got some ideas for improving the phrasing in the docs, definitely submit a PR.

**Comment by atkinchris** [comment]
Super. Thanks for the clarity and intent - we'll be careful not to use defaults in `mapStateToProps`.
