### ISSUE TITLE
Can't access ownProps from connect options object

### ISSUE THREAD

**Issue by marcselman** [reactjs/react-redux#648]
Hi,

I'm using `redux-form` to generate multiple forms on a page.
Each form has a dynamic name: `` `setter-${ ownProps.setter.id }` ``
The form field values are stored in the state in `state.form.[form-name]`
For performance reasons I want to compare only that part of the state using the `areStatesEqual` option.

But I think I can't access the `ownProps` from the `areStatesEqual` function.

Below is a simplified piece of my code:
```javascript
export default connect(
	(state, ownProps) => {
		const formName = `setter-${ ownProps.setter.id }`
		const selector = formValueSelector(formName)

		return {
			form: formName,
			selectedSetterType: selector(state, 'setterType'),
			initialValues: {
				setterType: ownProps.setter.takeValueFromPropertyId ? 'TakeValue' : 'FixedValue'
			}
		}
	}, {
	}, undefined, {
		areStatesEqual: (prev, next) => {
			//ownProps or formName needed here:
			//prev.form[`setter-${ ownProps.setter.id }`] == next.form[`setter-${ ownProps.setter.id }`]
			return true
		}
	}
)(
	reduxForm({
		enableReinitialize: true,
	})(PropertySetter)
)
```

Any idea how this could be accomplished?

**Comment by markerikson** [comment]
I'm not sure this is the right approach.  A few thoughts:

First, for readability, I generally suggest defining `mapState` and other similar functions separately, rather than inline inside of `connect`.  In that example, it's very hard to make out which arg is which.  I actually missed the empty object being passed as the `mapDispatch` arg at first because it blended in.  (Also, if you don't want any bound action creators, pass `null` or `undefined` for the `mapDispatch` arg rather than an empty object.)

Second, it doesn't look like props are passed to `areStatesEqual` at all, per [selectorFactory.js#L76](https://github.com/reactjs/react-redux/blob/f892ec00d7e92ff7afb21498276472f0e3b000c5/src/connect/selectorFactory.js#L76).

Third, I'm not sure that there's going to be an overly meaningful difference in perf between trying to compare parts of the entire state in `statesAreEqual`, and just using memoized selectors inside of `mapState` and letting `connect` diff the output of `mapState` as usual.

**Comment by jimbolla** [comment]
As @markerikson said, you're better off doing that optimization inside `mapStateToProps`.
