### ISSUE TITLE
Optional usage without context

### ISSUE THREAD

**Issue by everdimension** [reactjs/react-redux#650]
I have been wondering why dependence on context is not optional.

Context is always referred to as an unstable and experimental feature, although react and redux are stable libraries widely used in production.

It seems to me that passing a configured `store` explicitly to connect is no harder than passing  action creators to it. This would also mean that we don't need a `<Provider />` component, therefore less api surface area.

Would this update be desired? Or am I missing something and there are hidden complications i'm not considering?

**Comment by timdorr** [comment]
Context is fine. It's getting fleshed out more and more with each major version (there are finally docs for it) and it's not going away any time soon. 

Getting the right instance of the store might be difficult. If you have a singleton instance, that may work fine. But in the server context, that's a lot more tough to do. 

But passing in a store prop to a connected component or an option to connect() might be a good idea. It certainly wouldn't be a step backwards.

**Comment by BTMPL** [comment]
Was about to write exactly what @timdorr wrote - you can pass the store as prop:

https://github.com/reactjs/react-redux/blob/master/src/components/connectAdvanced.js#L122

**Comment by timdorr** [comment]
Oh duh, that's right. We've already got this! 😄

**Comment by markerikson** [comment]
Yeah, passing the store reference explicitly down the component tree _is_ possible, but also a pain.  That's why `<Provider>` exists in the first place.

Also, the general advice for using context is "Apps should probably avoid it, libraries _can_ use it, but either way you should really encapsulate how it's being used".  That way, ***when*** the API does change, you only have to update one or two places.

So yes, `connect` will have to be updated to match whatever the new API is when the time comes, but that'll be a major bump, and _we_ will handle doing that.  Ideally, _your_ app won't have to worry about it.

**Comment by everdimension** [comment]
Ok, thanks everyone for the answers, I glanced over `connectAdvanced` and saw its ties to the context and assumed that passing store as a prop wasn't supported.

I fully understand why having store in a single place is a convenient paradigm but I don't really see how passing store explicitly is "a pain". When your store instance is a singleton, passing it to connected components is as easy as passing bound action creators, like I mentioned.

But in a server context that's a bit a different story, I agree.

**Comment by markerikson** [comment]
@everdimension : yeah, there's an FAQ entry that addresses that: http://redux.js.org/docs/faq/StoreSetup.html#store-setup-multiple-stores .  Basically, accessing the store via context acts as a lightweight dependency injection mechanism, thus making it easier to test components, less hassle passing the store down, component reuse, etc.
