### ISSUE TITLE
Reactjs Proptypes v 15.5 warnings when using react-redux provider

### ISSUE THREAD

**Issue by iambchan** [reactjs/react-redux#677]
I'm currently using react-redux in our production environment with the latest version of react and react-redux, and it's generating thousands of warnings/console errors. 

I looked into the documentation in the reactjs proptypes
ttps://github.com/reactjs/prop-types#difference-from-reactproptypes-dont-call-validator-functions

```js
However, code like this will not work with the prop-types package:

// Will not work with `prop-types` package!
var errorOrNull = PropTypes.bool(42, 'myProp', 'MyComponent', 'prop');
```
https://github.com/reactjs/react-redux/blob/master/src/utils/PropTypes.js
and the code in the PropTypes.js file is basically doing what the docs say not to do:
```js
export const subscriptionShape = PropTypes.shape({
  trySubscribe: PropTypes.func.isRequired,
  tryUnsubscribe: PropTypes.func.isRequired,
  notifyNestedSubs: PropTypes.func.isRequired,
  isSubscribed: PropTypes.func.isRequired,
})
```
I replaced the subscriptionShape and storeShape to return an empty function that returns null and the errors went away, except a few more: 
```
Warning: Failed propType: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them. Read more at http://fb.me/use-check-prop-types Check the render method of `-`.
Warning: Failed Context Types: Provider: child context type `store` is invalid; it must be a function, usually from React.PropTypes. Check the render method of `-`.
```

Not entirely sure what to do next! Any assistance could be helpful!

**Comment by gaearon** [comment]
>and the code in the PropTypes.js file is basically doing what the docs say not to do:

This is not correct, and I apologize for the confusion. `shape()` **returns** a validator, it's not a validator itself. The incorrect behavior would be to call **the function it returns**. Calling `shape()` itself is absolutely fine, it's the public API.

**Comment by gaearon** [comment]
I just created a new app, and I don’t have this issue. I’m afraid that in order to help you we will need to see a full project that consistently reproduces it. For now I’ll close assuming a user mistake.

I checked `node_modules`, and I have `react-redux@5.0.4`, `react@15.5.4`, `react-dom@15.5.4`, and `prop-types@15.5.8` there. My intuition is you have an old version of some of these packages. Please double-check what’s really in your `node_modules`.

I’m happy to reopen this if you provide a project demonstrating the problem.
