### ISSUE TITLE
Call dispatch with more than one argument

### ISSUE THREAD

**Issue by eugeny-dementev** [reactjs/react-redux#682]
Original redux `dispatch` allow to pass more than one argument thats in result will be received in the middleware and all passed arguments will be logged. It's very useful and flexible. But `dispatch` function that passed to `mapDispatchToProps` handle only first argument and middleware always log array with that first argument.
```js
// Redux 3.6.0

const middlewares = [
  function logArguments (store) {
    return next => (...args) => {
      console.log(args);

      next(...args);
    }
  }
];

const store = createStore(() => {}, applyMiddleware(...middlewares));

store.dispatch({ type: 'NOOP' }, { arg: 'second' }, { arg: 'third' });
```
```
// [ { type: 'NOOP' }, { arg: 'second' }, { arg: 'third' } ]
```
Actually i didn't find any documentation about this way to use `dispatch` so it'll be nice to also clarify that moment.

**Comment by markerikson** [comment]
This is a question regarding Redux, not React-Redux.  In particular, this was heavily discussed in https://github.com/reactjs/redux/pull/1813 .  As a quick summary of that thread, it won't work because the entire ecosystem assumes that only one thing is passed to dispatch at a time.  If you're looking to batch up dispatched actions (especially to minimize the number of subscriber notifications), there's a variety of possible batching addons you can use, such as https://github.com/manaflair/redux-batch .

**Comment by eugeny-dementev** [comment]
Thank you. You were right, the issue is about ecosystem. It was previuos middleware thats handle and pass to next callback only one argument.
