### ISSUE TITLE
Allow setting connect defaults at Provider level. 

### ISSUE THREAD

**Issue by guy-kdm** [reactjs/react-redux#688]
There's lots of back and forth regarding dropping SCU. For users who don't need this optimization it might cause unnecessary headaches with update blocking. If those users can turn it of at the provider level once they won't have to worry about it. Would you consider a PR that allows something like:
```jsx
<Provider store={} connectDefaults={{pure: false}}>
...
</Provider>
```

**Comment by timdorr** [comment]
The problem is `connect` functions outside of React, so it can't get defaults over context like that. 

However, in 5.x, implementing your own `connect` is actually pretty simple. It just wraps `connectAdvanced`, so you can copy the current wrapper and tweak the defaults in your own version: https://github.com/reactjs/react-redux/blob/master/src/connect/connect.js

**Comment by guy-kdm** [comment]
Yeah, it's just uncommon and someone will accidentally import from redux. So I was hopping for some global config but I guess I'll monkey patch somehow or just do it like that. Thanks for the tip!
