### ISSUE TITLE
render is called during or after dispatch depending on how dispatch was called

### ISSUE THREAD

**Issue by insolite** [reactjs/react-redux#705]
Depending on how dispatch was called, `render` method is called after `dispatch` or during `dispatch`, increasing total dispatch execution time.
I've created a tiny example project to explain it (look at console logs for operations order):
https://codesandbox.io/s/XoLlRLMxl
In 1st case (plain) we call `dispatch` directly and have the following order:
```
action
reducer
dispatch: 0.345947265625ms
render
```
In 2nd case (promise) we call `dispatch` from inside promise resolve callback and constantly getting a different order:
```
action
reducer
render
dispatch: 1.508056640625ms
```
3rd case (setTimeout) is leading to the same order as 2nd

Probably 2nd and 3rd case are ok and render stuff + dispatch itself taking the same time in total as in 1st case. But when we need to dispatch two or more actions after resolving promise we will get a huge overhead (that's how I discovered this issue). So is it a bug or supposed to be? And if that's ok then could it be controlled somehow?

**Comment by markerikson** [comment]
I'm pretty sure this is related to how React handles events and batches re-renders.  Depending on the source of the event (user interaction vs async event), I _think_ it handles re-rendering sync vs async.  Unlikely there's anything specific about this on the React-Redux side.

Pinging @timdorr , @jimbolla , and @gaearon for confirmation.

**Comment by timdorr** [comment]
We update via setState, which is batched and occurs on the next tick. This is just a matter of enqueuing messages in different orders for that next tick. 

This could be solved via redux-thunk/redux-promise, no?

**Comment by jimbolla** [comment]
What Tim said. My understanding is that setState will behave differently in React 16, so I don't think there's anything for us to do here.

**Comment by gaearon** [comment]
setState does not change behavior in 16, but will likely do in 17.

**Comment by GuichiZhao** [comment]
```
//use thunk
const thunkActionCreator=()=>dispatch=>Promise.resolve(dispatch({type:'FOO'}));
const action=getActionSomehow(thunkActionCreator);
action.then(()=>{
    //can I say the updates triggered by action live here, or if the re-render is guaranteed to be completed or not
})
```

**Comment by GuichiZhao** [comment]
Sorry guys, I am not hassling on purpose. But I think this issue has an important implication which is exactly what I care about : 
After `dispatch` is called if there is a guaranteed way to get the latest UI state. i.e. componentDidUpdate is completed.

As we know, after `dispatch` is invoked in thunked action creator, we can get the updated state using `getState`. However, `render` may not be invoked at all because redux/react will try to batch updates when all the dispatch is called and only trigger once. And batching process depends on how `dispatch` is triggered, i.e. if `dispatch` is triggered in an async way such as promise or timeout. The `render` from the last dispatch SHOULD be completed. I am 99% sure about it, just post here to confirm

@timdorr said I am thinking React in an imperative way. Because he believed I try to do things step 
by step rather than specify the state and let React to sort it out.

But, It is a quite common pattern in redux to dispatch another action based on the state updated by the previous action in action creator. Why not dispatch an action based on the UI updated by the previous action? Also, I think we are so close now:  just invoked `dispatch` in a dummy promise all 0 timeout

What is wrong with the idea? an anti-pattern or an unreliable way which is subject to change in future? @gaearon 

By the way, here is a brief of my use case: I need to `getBoundingClientRect` after the previous dispatch, that is why I care about if render is completed or not

**Comment by timdorr** [comment]
If you need to run after rendering has finished, use the React lifecycle. componentDidUpdate is exactly what you're looking for. 

Ultimately, this isn't something for Redux to solve. It's just how React behaves. It's just a matter of looking in the wrong place. You shouldn't look to Redux or connect() to ensure rendering guarantees. That's React's job and it's got lifecycle methods for it.
