### ISSUE TITLE
SyntaxError: Unexpected token import 

### ISSUE THREAD

**Issue by wood1986** [reactjs/react-redux#713]
I am using webpack to output a library for node to run and I did tell webpack not to do any bundling for `/^lodash/`.

Here is the error when I run the output js

```
node_modules/lodash-es/isPlainObject.js:1
(function (exports, require, module, __filename, __dirname) { import baseGetTag from './_baseGetTag.js';
                                                              ^^^^^^
```

 I did check the js ouput and I find the followings

```
/* 48 */
/***/ (function(module, exports) {

module.exports = require("lodash-es/isPlainObject");

/***/ }),
```

I can run the output js after changing `lodash-es` to `lodash`. 

Is it a bug? if so, react-redux or webpack issue?

**Comment by markerikson** [comment]
This is definitely not anything to do with React-Redux.

**Comment by leebenson** [comment]
Seeing the same issue here: https://github.com/reactql/examples/issues/3

The issue is that `lodash-es` is ES6 code, and if you're building your own Webpack bundle to target node, chances are you're not transpiling into `node_modules` -- just your own code.

I see there's [this file](https://github.com/reactjs/react-redux/blob/f892ec00d7e92ff7afb21498276472f0e3b000c5/build/use-lodash-es.js) which controls if `lodash-es` should be used.

I guess it'd be possible to update that file to have some environment awareness and avoid using `lodash-es` if running via Node (there's zero benefit to using the -es versions there, since Node is gonna grumble as soon as it hits an `import`).
