### ISSUE TITLE
Export createConnect in index.js

### ISSUE THREAD

**Issue by chromakode** [reactjs/react-redux#746]
For custom/extended uses of react-redux, `connectAdvanced` and `createProvider` are exported from [`index.js`](https://github.com/reactjs/react-redux/blob/1a39f71a52905edb0f119603632f143154deab3b/src/index.js), but `createConnect` is not. Is this intentional, or would you consider adding it?

**Comment by timdorr** [comment]
It's intentional. `createConnect` is just a convenience function for us to wrap up all the boilerplate around using `connectAdvanced`. It's really only 4 lines of code when you take out all the line breaks and extraneous stuff. You should just use `connectAdvanced` directly, making it specifically customized to your own use case.

**Comment by chromakode** [comment]
Thanks for the explanation! :+1:
