### ISSUE TITLE
MapStateToProps() is not called when updating state with Immutable.js

### ISSUE THREAD

**Issue by j-o-d-o** [reactjs/react-redux#771]
I am updating the state in the reducer like this (its a nested Map and inside there is an List):

`return state.updateIn(["config", "layers"], layers => layers.set(index, action.layer));`

The redux store is changed successfully, but the react component does not receive the changed props.
In order to get it working and recive the changed props inside the react component I have to delete the old element and push to the array again:

```
let newState = state.updateIn(["config", "layers"], layers => layers.delete(index));
return newState.updateIn(["config", "layers"], list => list.push(action.layer));
```

To me this seems like a bug, or is this the desired behavior?

**Comment by timdorr** [comment]
If you're returning the same object or array instance (newState === oldState), then that's entirely expected behavior. But if you're supposed to be returning a new instance (as is the case with immutable.js), then something else is going wrong. I would check that you're actually replacing the instance.
