### ISSUE TITLE
Improving API for connecting components

### ISSUE THREAD

**Issue by edahlseng** [reactjs/react-redux#782]
I've been using React-Redux for a while now, and I feel like there's room to improve the connect() API. Currently the process for connecting a React component looks like this:
```javascript
import { connect } from 'react-redux'

const TodoList = ({ todos, onTodoClick }) => (
  <ul>
    {todos.map(todo => (
      <Todo key={todo.id} {...todo} onClick={() => onTodoClick(todo.id)} />
    ))}
  </ul>
)

const mapStateToProps = state => {
    return {
        todos: state.todos
    }
}

const mapDispatchToProps = dispatch => {
    return {
        onTodoClick: id => {
            dispatch(toggleTodo(id))
        }
    }
}

const VisibleTodoList = connect(
    mapStateToProps,
    mapDispatchToProps
)(TodoList)
```

Defining several different functions and then using them to "connect" the component feels messier than it needs to be. One possible alternative could be to use something more like this:

```javascript
class TodoList extends Redux.Component {
     constructor(props) {
        super(props, {
            stateToProps: state => {
                return { todos: state.todos }
            },
            dispatchToProps: dispatch => {
                return {
                    onTodoClick: id => {
                        dispatch(toggleTodo(id))
                    }
            }
        })
     }

    render() {
        return (
            <ul>
                {todos.map(todo => (
                    <Todo key={todo.id} {...todo} onClick={() => onTodoClick(todo.id)} />
                ))}
            </ul>
         )
    }
}
```

Where Redux.Component would essentially act as a wrapper around React.Component. This alternative would keep the mappings contained within the relevant component, and would help prevent the creation of excess components. This approach in particular does require a class component instead of functional components, but I'd argue that's an okay requirement, which follows the same mental model where only class components have access to local state.

I'm not saying the proposed change is the best option, I'm just hoping that we can have a good discussion about this.

**Comment by markerikson** [comment]
I'll leave this open for now (even though discussion can continue on closed issues), but I really don't see any point or benefit to that kind of approach.  The current API has been pretty stable since shortly after React-Redux was split out as a separate lib, and there's no particular reason to go making changes to it.

What specific pain points are you having with the current API?  What do you mean by "prevent creation of excess components"?  

Also, the current API absolutely allows you to connect functional components, and some people even go so far as to _only_ use functional components connected to Redux, with no class components at all.  (I personally think that's way too dogmatic, but it's a possible stylistic approach.)  Anything that would drop the ability to connect functional components is absolutely a non-starter.

**Comment by timdorr** [comment]
I disagree with that being messy. You can use inline, anonymous functions if you don't want to create something separate. But this is just basic functional design. That's how JS works.

Also, extending React.Component is a bad idea. You immediately run into the issues of multiple inheritance. What if you want a component that is both a Redux component and another library's component? Higher-order Components let you wrap things in a functional way, using the language rather than fighting against it.

**Comment by edahlseng** [comment]
Thanks for the responses. In general I think I find some parts of Redux to be more complicated than they need to be, and I was trying to find some low hanging fruit to make improvements. I wasn't aware of the concept of higher-order components, but after reading the [React document about them](https://facebook.github.io/react/docs/higher-order-components.html), I totally see their benefits, and now I understand why `connect()` API is structured the way it is.

Honestly, after learning about higher-order components, I feel very silly for even opening this issue in the first place. Thank you both for being respectful towards my stupid idea!

**Comment by timdorr** [comment]
No worries. I wouldn't call the idea stupid; just lacking complete context. You were trying to make a table and didn't know hammers existed, so suggested using screws. Now that you know about hammers, you have some better ideas of how to build that table. :smile:

**Comment by markerikson** [comment]
Yep.

Out of curiosity, what else are you thinking of as far as "parts of Redux being more complicated than they need to be"?

You might also be interested in reading through my two-part post [The Tao of Redux, Part 1 - Implementation and Intent](http://blog.isquaredsoftware.com/2017/05/idiomatic-redux-tao-of-redux-part-1/) and [The Tao of Redux, Part 2 - Practice and Philosophy](http://blog.isquaredsoftware.com/2017/05/idiomatic-redux-tao-of-redux-part-2/), where I go through a lot of the history and design of Redux, and why specific usage patterns exist in the first place.

**Comment by edahlseng** [comment]
It's just a general gut feeling that I get when using Redux. It seems like there are so many different parts -- actions, reducers, presentation components, container components, side effects, etc. that it makes it hard to internalize into one simple description.

As an example, consider React on it's own. You could describe the general organization of a React app in a single sentence: "A single parent component is created, which creates child components, which then create their own child components, and so on." And I know that if I step out of a React codebase for even several months, I'll be able to come back and get re-situated relatively quickly. With Redux, I'm not able to describe the organization in a single sentence, and I feel disoriented whenever I return to a Redux codebase after some time away.

All of this might simply be due to a lack of experience with Redux, or due to how I've been organizing my applications. Thanks for linking those posts -- I expect they will help clarify a few things for me!
