### ISSUE TITLE
Is the library provide a similar API like the callback in `setState` in React

### ISSUE THREAD

**Issue by GuichiZhao** [reactjs/react-redux#789]
The callback in `setState` can guarantee the render is finished when invoking. Did redux expose similar API?

Here is detailed description of the problem
https://stackoverflow.com/questions/46271899/how-can-i-make-sure-render-is-completed-in-redux

Basically, both `setState` in React and `dispatch` in Redux update the UI somehow. If React provides a callback when `render` is completed, why not Redux? Is there a reliable way to achieve this already?

**Comment by timdorr** [comment]
Because there is no direct connection between dispatching an action and re-rendering a component. Redux doesn't depend on React at all, so they are two separate APIs entirely. 

You shouldn't be concerned with knowing that a certain dispatch caused a certain render. You're attempting to take an imperative approach to React's declarative architecture. Just wait for the appropriate lifecycle event and render your UI appropriately based on the current state.
