### ISSUE TITLE
React native provider does not support toggle inspector

### ISSUE THREAD

**Issue by juangallo** [reactjs/react-redux#817]
When I try to inspect some elements on the device the provider gives me some error.
<img width="309" alt="screen shot 2017-10-26 at 11 18 37 am" src="https://user-images.githubusercontent.com/14864292/32058092-81c0bf52-ba3f-11e7-955f-246717e8022b.png">

**Comment by timdorr** [comment]
https://github.com/reactjs/react-redux/issues/347#issuecomment-208964023

**Comment by ghost91-** [comment]
How does [#347 (comment)](https://github.com/reactjs/react-redux/issues/347#issuecomment-208964023) have anything to do with the issue described here?

Toggeling the inspector wroked fine for me until very recently. SInce a few days I am getting the error message from the screenshot posted by @juangallo
