### ISSUE TITLE
reducer goes into a loop when returning a new array created from state

### ISSUE THREAD

**Issue by boris-layvant** [reactjs/react-redux#832]
I have a reducer containing the following code:
```javascript
export default (state = [], action) => {
  switch(action.type) {
    case 'ADD_ENGAGEMENT':
      let newArr = state.slice();
      newArr.push(action.payload);
      return newArr;
    case 'UPDATE_ENGAGEMENT':
      console.info('UPDATE_ENGAGEMENT')
      return state.slice();
      // return state;
    default:
      return state;
  }
}
```
The issue occurs within the 'UPDATE_ENGAGEMENT' case -- the actual business logic has been removed and replaced with the simplest example to demonstrate the problem. 

When a new array created from state via state.slice() is returned, a loop is triggered, causing the action to be dispatched until an 'Uncaught RangeError: Maximum call stack size exceeded' error is raised. Below is a screenshot of the browser console during the issue's occurrence.

![screen shot 2017-11-30 at 10 36 07 am](https://user-images.githubusercontent.com/6816554/33439444-6e2f30da-d5bb-11e7-92a2-b86baa9c5954.png)

When the original state is returned, the issue does not occur.
I am completely baffled by this behavior and cannot fathom how anything in my application could be causing it. Any insight would be immensely appreciated.

**Comment by boris-layvant** [comment]
I forgot to mention that the version of react-redux is 5.0.6

**Comment by boris-layvant** [comment]
The issue is not limited to 'slice()' and occurs whenever an array containing any element of state is returned e.g. return [state[0]]

**Comment by markerikson** [comment]
This is a bug tracker, not a support system. For usage questions, please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out - you'll probably get a better answer faster. Thanks!

That said, it's also very hard to understand what the issue is without seeing the rest of your code.  My immediate guess is that you have a component that's dispatching the action in `componentWillReceiveProps` or something similar, thus causing the infinite loop.

**Comment by anniewey** [comment]
@boris-layvant Did you found any solution?
