### ISSUE TITLE
Can mutate state when using remove on array from redux store

### ISSUE THREAD

**Issue by ntomallen** [reactjs/react-redux#940]
I'm using this with `react-native`, and I have spent all afternoon tracking down a bug where part of my state (an array) kept getting emptied! I tracked it down to a part of my codebase where I use `connect` to map the array into the props of a component, then within a child component I use `remove` on the array to remove some elements that I do not wish to be displayed. Essentially, I was noticing that the entire redux state object for that array was being mutated here. In redux, the array had 12 elements, but after the remove function in a component, it has 0 elements (in this case, the remove function was correctly removing all elements from the array). To fix this issue, I created a copy of the array using the spread syntax and instead called remove on this copied array.

My expectation is that when getting a state object out of my redux store, I would not be able to affect the redux store by changing the state in my react component. However, it definitely seems to be happening!

Of course, this isn't a hard workaround (and it definitely wouldn't be a bad idea to stop using remove), but I wasn't aware this was even possible. Is this intended behavior and do I need to ensure that I never mutate state objects I get out of redux, or is this a bug?

If needed, I can try to make a small, reproducible example. I wanted to check and see if this is how it works by design first. Thanks!

**Comment by markerikson** [comment]
Javascript objects are mutable by default - it's how the language was designed.  All Redux does is add a small wrapper around storing a current value.  If you call `getState()`, you have a reference to whatever object or array your root reducer returned, and it's entirely possible for you to mutate it, because that's how Javascript works.  So yes, it's on you to ensure you don't accidentally mutate your state.  Redux just provides a pattern to help you structure the update logic.

There are various middlewares you can use in development to catch accidental mutations by freezing your state, and there are common libraries and utilities you can use to help make sure you do your updates immutably.  Please see the [Immutable Update Patterns](https://redux.js.org/recipes/structuring-reducers/immutable-update-patterns) docs section, and the [DevTools#Mutation Detection](https://github.com/markerikson/redux-ecosystem-links/blob/master/devtools.md#mutation-detection) section of the Redux addons catalog.
